#!/bin/bash

if command -v java &> /dev/null; then
    _java=$(which java)
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
else
    echo "You do not have Java installed."
    exit
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    if [[ "$version" < "18" ]]; then
        echo "Your Java version is '$version' and aloft requires at least version 18."
        exit 1
    fi
fi

#sudo -u aloft -D /home/aloft run ...
java -jar /usr/local/lib/aloft/server/server.jar "$@"